# Generated by Django 3.0.2 on 2021-02-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20210207_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=30, unique=True)),
                ('stock_symbol', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
