# Generated by Django 3.0.2 on 2021-02-23 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_stocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name_plural': 'Stocks'},
        ),
        migrations.AddField(
            model_name='account',
            name='money',
            field=models.FloatField(default=10000),
        ),
        migrations.CreateModel(
            name='Open',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.FloatField()),
                ('purchased_at', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('stock', models.ManyToManyField(blank=True, related_name='open', to='shares.Stocks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_positions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Closed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.FloatField()),
                ('closed_at', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('stock', models.ManyToManyField(blank=True, related_name='closed', to='shares.Stocks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_positions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
