# Generated by Django 3.0.2 on 2021-02-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0004_auto_20210224_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closed',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='open',
            name='purchased_at',
        ),
        migrations.AddField(
            model_name='closed',
            name='gains',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000000000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open',
            name='position',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000000000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='money',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10000000000000),
        ),
    ]
