# Generated by Django 3.0.2 on 2021-02-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_auto_20210227_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closed',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='open',
            name='stock',
        ),
        migrations.AddField(
            model_name='closed',
            name='stock_symbol',
            field=models.CharField(default='AAPL', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open',
            name='stock_symbol',
            field=models.CharField(default='AAPL', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
